-- require("core.plugin_config.tokyonight")
-- require("core.plugin_config.gruvbox")
-- require("core.plugin_config.nightfox")
require("core.plugin_config.kanagawa")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.lualine")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.vim-test")
require("core.plugin_config.completions")
require("core.plugin_config.lsp_config")
require("core.plugin_config.autopairs")
require("core.plugin_config.toggleterm")

